#!/usr/bin/env bash
# RunPod one-time setup for the VoxReach POC (PersonaPlex variant).
#
# Installs everything onto the persistent network volume at /workspace so the
# install survives pod recycle/termination. After this runs once, future pods
# only need to re-attach the network volume and run runpod/start.sh.
#
# Override WORKSPACE if your network volume is mounted somewhere other than
# /workspace.

set -euo pipefail

# Verbose progress — every command echoes before running. Toggle with QUIET=1.
if [ "${QUIET:-0}" != "1" ]; then
  set -x
fi

# Phase timing helpers
_phase_t0=0
phase_start() {
  _phase_t0=$(date +%s)
  set +x
  echo ""
  echo "═══════════════════════════════════════════════════════════════════════"
  echo "  $1"
  echo "═══════════════════════════════════════════════════════════════════════"
  if [ "${QUIET:-0}" != "1" ]; then set -x; fi
}
phase_done() {
  set +x
  local elapsed=$(( $(date +%s) - _phase_t0 ))
  echo "─── done in ${elapsed}s ───"
  if [ "${QUIET:-0}" != "1" ]; then set -x; fi
}

WORKSPACE="${WORKSPACE:-/workspace}"
POC_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -d "${WORKSPACE}" ]; then
  echo "!! ${WORKSPACE} does not exist. Attach the persistent network volume"
  echo "   in the RunPod console at mount path /workspace, then re-run this script."
  echo "   (Or override WORKSPACE=<your-path> if mounted elsewhere.)"
  exit 1
fi

# Persistent install paths — all on the network volume
PP_VENV="${PP_VENV:-${WORKSPACE}/.venv/voxreach-personaplex}"
SIDECAR_VENV="${SIDECAR_VENV:-${POC_DIR}/sidecar/.venv}"
PERSONAPLEX_REPO="${PERSONAPLEX_REPO:-${WORKSPACE}/personaplex}"

export HF_HOME="${HF_HOME:-${WORKSPACE}/.cache/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-${WORKSPACE}/.cache/pip}"

echo "==> POC dir:           ${POC_DIR}"
echo "==> Workspace:         ${WORKSPACE}"
echo "==> PersonaPlex repo:  ${PERSONAPLEX_REPO}"
echo "==> PersonaPlex venv:  ${PP_VENV}"
echo "==> Sidecar venv:      ${SIDECAR_VENV}"
echo "==> HF cache:          ${HF_HOME}"
echo "==> pip cache:         ${PIP_CACHE_DIR}"

mkdir -p "${HF_HOME}" "${PIP_CACHE_DIR}" "$(dirname "${PP_VENV}")"

# ---------------------------------------------------------------------------
# Write a sourceable env file on the persistent volume.
# Future pods just `source /workspace/.voxreach.env` to inherit all paths.
# ---------------------------------------------------------------------------
ENV_FILE="${WORKSPACE}/.voxreach.env"
cat > "${ENV_FILE}" <<EOF
# VoxReach POC env — auto-generated by runpod/setup.sh
# Source this on every new pod before running runpod/start.sh
export WORKSPACE=${WORKSPACE}
export PP_VENV=${PP_VENV}
export PERSONAPLEX_REPO=${PERSONAPLEX_REPO}
export HF_HOME=${HF_HOME}
export HUGGINGFACE_HUB_CACHE=${HUGGINGFACE_HUB_CACHE}
export TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE}
export PIP_CACHE_DIR=${PIP_CACHE_DIR}
EOF
echo "==> Wrote env file: ${ENV_FILE}"

# Also persist for this pod's interactive shells
if ! grep -q 'voxreach.env' ~/.bashrc 2>/dev/null; then
  echo "" >> ~/.bashrc
  echo "# VoxReach POC env (auto-added by setup.sh)" >> ~/.bashrc
  echo "[ -f ${ENV_FILE} ] && source ${ENV_FILE}" >> ~/.bashrc
fi

# ---------------------------------------------------------------------------
# System packages
# ---------------------------------------------------------------------------
phase_start "[1/8] System packages (opus, ffmpeg, tmux, jq, git)"
apt-get update
apt-get install -y libopus-dev ffmpeg tmux jq curl git
apt-get clean
rm -rf /var/lib/apt/lists/*
phase_done

# ---------------------------------------------------------------------------
# HF auth check
# ---------------------------------------------------------------------------
echo ""
if [ -z "${HF_TOKEN:-}" ]; then
  echo "!! HF_TOKEN is not set in this pod's environment."
  echo "   1. Generate a token at https://huggingface.co/settings/tokens"
  echo "   2. Accept the license at https://huggingface.co/nvidia/personaplex-7b-v1"
  echo "   3. Set HF_TOKEN as a secret on this RunPod pod, then re-run."
  exit 1
fi
export HUGGING_FACE_HUB_TOKEN="${HF_TOKEN}"
echo "==> HF_TOKEN is set (length=${#HF_TOKEN})"

# ---------------------------------------------------------------------------
# Upgrade pip globally
# ---------------------------------------------------------------------------
phase_start "[2/8] Upgrading global pip"
python3 -m pip install --upgrade pip
phase_done

# ---------------------------------------------------------------------------
# Sidecar venv (lightweight — lives next to the repo on /workspace)
# ---------------------------------------------------------------------------
phase_start "[3/8] Sidecar venv at ${SIDECAR_VENV}"
mkdir -p "$(dirname "${SIDECAR_VENV}")"
# If a partial/broken venv exists (common after pod migration), nuke it
if [ -d "${SIDECAR_VENV}" ] && ! "${SIDECAR_VENV}/bin/python" -c "import sys" 2>/dev/null; then
  echo "    (existing venv is broken — recreating)"
  rm -rf "${SIDECAR_VENV}"
fi
if [ ! -d "${SIDECAR_VENV}" ]; then
  python3 -m venv "${SIDECAR_VENV}"
fi
# shellcheck disable=SC1091
source "${SIDECAR_VENV}/bin/activate"
pip install --upgrade pip
pip install \
  "fastapi>=0.115" \
  "uvicorn[standard]>=0.32" \
  "pydantic>=2.9" \
  "httpx>=0.27" \
  "sse-starlette>=2.1" \
  "python-multipart>=0.0.12"
deactivate
phase_done

# ---------------------------------------------------------------------------
# Clone NVIDIA/personaplex repo (moshi fork with PersonaPlex defaults)
# ---------------------------------------------------------------------------
phase_start "[4/8] NVIDIA/personaplex source at ${PERSONAPLEX_REPO}"
# Fresh clone if missing OR if the moshi/ subdir is gone (happens when a pod
# migration only preserves partial files on the persistent volume).
if [ ! -d "${PERSONAPLEX_REPO}" ] || [ ! -d "${PERSONAPLEX_REPO}/moshi" ]; then
  echo "    (no usable checkout found — cloning fresh)"
  rm -rf "${PERSONAPLEX_REPO}"
  git clone https://github.com/NVIDIA/personaplex "${PERSONAPLEX_REPO}"
elif [ -d "${PERSONAPLEX_REPO}/.git" ]; then
  (cd "${PERSONAPLEX_REPO}" && git pull --ff-only) || true
else
  echo "    (existing checkout has no .git but moshi/ present — using on-disk source as-is)"
fi
# Sanity — must have the moshi package to install
[ -f "${PERSONAPLEX_REPO}/moshi/pyproject.toml" ] || {
  echo "!! ${PERSONAPLEX_REPO}/moshi/pyproject.toml not found — clone is incomplete."
  exit 1
}
phase_done

# ---------------------------------------------------------------------------
# PersonaPlex venv — install NVIDIA's fork of moshi (not PyPI's vanilla moshi)
# ---------------------------------------------------------------------------
phase_start "[5/8] PersonaPlex venv at ${PP_VENV} (heavy — torch + moshi)"
mkdir -p "$(dirname "${PP_VENV}")"
# If a partial/broken venv exists (common after pod migration — pip's
# pip._internal goes missing), nuke and recreate from scratch.
if [ -d "${PP_VENV}" ] && ! "${PP_VENV}/bin/python" -c "import sys" 2>/dev/null; then
  echo "    (existing PP venv is broken — recreating)"
  rm -rf "${PP_VENV}"
fi
if [ ! -d "${PP_VENV}" ]; then
  python3 -m venv "${PP_VENV}"
fi
# shellcheck disable=SC1091
source "${PP_VENV}/bin/activate"
pip install --upgrade pip
echo "==> Installing NVIDIA moshi fork from ${PERSONAPLEX_REPO}/moshi ..."
pip install "${PERSONAPLEX_REPO}/moshi"
pip install huggingface_hub hf_transfer accelerate
phase_done

# Customer-side STT deps — webrtcvad for utterance segmentation, faster-whisper
# (CTranslate2 backend) for transcription. We deliberately avoid transformers/
# Kyutai-STT here: Kyutai's model_type "stt" isn't supported by transformers
# v4.x, and pulling in transformers v5 cascades into a numpy/safetensors/hub
# fight with moshi-personaplex's declared pins.
phase_start "[6/8] Customer-side STT deps (setuptools<80 + webrtcvad + faster-whisper)"
# setuptools 80+ removed pkg_resources entirely, and webrtcvad's top-level
# __init__ does `import pkg_resources`. With a default fresh-pod install pip
# resolves to setuptools 82, the webrtcvad import explodes silently, and the
# STT bridge disables itself. Pin to <80 so pkg_resources is still bundled.
pip install \
  "setuptools>=70,<80" \
  "webrtcvad>=2.0.10" \
  "faster-whisper>=1.0.0"
# Verify the install actually works — fail loudly if pkg_resources is missing
python -c "import pkg_resources, webrtcvad, faster_whisper; print('STT imports ok')" \
  || { echo "!! STT imports failed — see setuptools version above"; exit 1; }
phase_done

# Apply VoxReach patches (idempotent) — adds server-side default text prompt
echo "==> Applying VoxReach patches to moshi/server.py ..."
SERVER_PY=$(ls "${PP_VENV}"/lib/python*/site-packages/moshi/server.py 2>/dev/null | head -1)
if [ -n "${SERVER_PY}" ]; then
  python "${POC_DIR}/runpod/patches/inject_default_prompt.py" "${SERVER_PY}" || \
    echo "    (patch failed — server will work, but the default-prompt feature won't activate)"
fi

# Quick CUDA sanity — fail fast if torch can't talk to the GPU
python - <<'PY'
import torch
print(f"   torch       {torch.__version__}")
print(f"   cuda        {torch.cuda.is_available()}")
if not torch.cuda.is_available():
    raise SystemExit("ERROR: torch.cuda.is_available() is False — wrong CUDA wheels for this pod's driver")
print(f"   GPU         {torch.cuda.get_device_name(0)}")
print(f"   VRAM        {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
PY

# ---------------------------------------------------------------------------
# Pre-pull weights — both calls are no-ops when the HF cache already has them
# ---------------------------------------------------------------------------
phase_start "[7/8] HF weights (cache hits = near-instant)"
echo "==> PersonaPlex 7B (~14 GB) — should be cached:"
python - <<'PY'
import os
from huggingface_hub import snapshot_download
snapshot_download(repo_id="nvidia/personaplex-7b-v1", token=os.environ["HUGGING_FACE_HUB_TOKEN"])
print("   personaplex-7b-v1 ready")
PY

if [ "${VOXREACH_SKIP_STT_PREFETCH:-0}" != "1" ]; then
  STT_MODEL_ID="${VOXREACH_STT_MODEL:-Systran/faster-distil-whisper-large-v3}"
  echo "==> faster-whisper ${STT_MODEL_ID} (~1.5 GB) — should be cached:"
  python - <<PY
import os
from huggingface_hub import snapshot_download
snapshot_download(repo_id="${STT_MODEL_ID}", token=os.environ.get("HUGGING_FACE_HUB_TOKEN"))
print("   ${STT_MODEL_ID} ready")
PY
fi

deactivate
phase_done

# ---------------------------------------------------------------------------
# Node + web app
# ---------------------------------------------------------------------------
phase_start "[8/8] Node 20 + web app deps"
if ! command -v node >/dev/null 2>&1; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
cd "${POC_DIR}/web"
npm ci
phase_done

# ---------------------------------------------------------------------------
set +x
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo "  SETUP COMPLETE"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Disk usage:"
df -h / "${WORKSPACE}" 2>/dev/null | head -3
echo ""
echo "Env file: ${ENV_FILE}"
echo ""
echo "Next: apply runtime patches and start services"
echo "  bash ${POC_DIR}/runpod/apply_patches.sh"
echo "  bash ${POC_DIR}/runpod/start.sh"
