#!/usr/bin/env bash
# RunPod one-time setup for the VoxReach POC (PersonaPlex variant).
#
# Installs everything onto the persistent network volume at /workspace so the
# install survives pod recycle/termination. After this runs once, future pods
# only need to re-attach the network volume and run runpod/start.sh.
#
# Override WORKSPACE if your network volume is mounted somewhere other than
# /workspace.

set -euo pipefail

WORKSPACE="${WORKSPACE:-/workspace}"
POC_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -d "${WORKSPACE}" ]; then
  echo "!! ${WORKSPACE} does not exist. Attach the persistent network volume"
  echo "   in the RunPod console at mount path /workspace, then re-run this script."
  echo "   (Or override WORKSPACE=<your-path> if mounted elsewhere.)"
  exit 1
fi

# Persistent install paths — all on the network volume
PP_VENV="${PP_VENV:-${WORKSPACE}/.venv/voxreach-personaplex}"
SIDECAR_VENV="${SIDECAR_VENV:-${POC_DIR}/sidecar/.venv}"
PERSONAPLEX_REPO="${PERSONAPLEX_REPO:-${WORKSPACE}/personaplex}"

export HF_HOME="${HF_HOME:-${WORKSPACE}/.cache/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-${WORKSPACE}/.cache/pip}"

echo "==> POC dir:           ${POC_DIR}"
echo "==> Workspace:         ${WORKSPACE}"
echo "==> PersonaPlex repo:  ${PERSONAPLEX_REPO}"
echo "==> PersonaPlex venv:  ${PP_VENV}"
echo "==> Sidecar venv:      ${SIDECAR_VENV}"
echo "==> HF cache:          ${HF_HOME}"
echo "==> pip cache:         ${PIP_CACHE_DIR}"

mkdir -p "${HF_HOME}" "${PIP_CACHE_DIR}" "$(dirname "${PP_VENV}")"

# ---------------------------------------------------------------------------
# Write a sourceable env file on the persistent volume.
# Future pods just `source /workspace/.voxreach.env` to inherit all paths.
# ---------------------------------------------------------------------------
ENV_FILE="${WORKSPACE}/.voxreach.env"
cat > "${ENV_FILE}" <<EOF
# VoxReach POC env — auto-generated by runpod/setup.sh
# Source this on every new pod before running runpod/start.sh
export WORKSPACE=${WORKSPACE}
export PP_VENV=${PP_VENV}
export PERSONAPLEX_REPO=${PERSONAPLEX_REPO}
export HF_HOME=${HF_HOME}
export HUGGINGFACE_HUB_CACHE=${HUGGINGFACE_HUB_CACHE}
export TRANSFORMERS_CACHE=${TRANSFORMERS_CACHE}
export PIP_CACHE_DIR=${PIP_CACHE_DIR}
EOF
echo "==> Wrote env file: ${ENV_FILE}"

# Also persist for this pod's interactive shells
if ! grep -q 'voxreach.env' ~/.bashrc 2>/dev/null; then
  echo "" >> ~/.bashrc
  echo "# VoxReach POC env (auto-added by setup.sh)" >> ~/.bashrc
  echo "[ -f ${ENV_FILE} ] && source ${ENV_FILE}" >> ~/.bashrc
fi

# ---------------------------------------------------------------------------
# System packages
# ---------------------------------------------------------------------------
echo ""
echo "==> Installing system packages (opus, ffmpeg, tmux, jq) ..."
apt-get update -qq
apt-get install -y -qq libopus-dev ffmpeg tmux jq curl git
apt-get clean
rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------------------
# HF auth check
# ---------------------------------------------------------------------------
echo ""
if [ -z "${HF_TOKEN:-}" ]; then
  echo "!! HF_TOKEN is not set in this pod's environment."
  echo "   1. Generate a token at https://huggingface.co/settings/tokens"
  echo "   2. Accept the license at https://huggingface.co/nvidia/personaplex-7b-v1"
  echo "   3. Set HF_TOKEN as a secret on this RunPod pod, then re-run."
  exit 1
fi
export HUGGING_FACE_HUB_TOKEN="${HF_TOKEN}"
echo "==> HF_TOKEN is set (length=${#HF_TOKEN})"

# ---------------------------------------------------------------------------
# Upgrade pip globally
# ---------------------------------------------------------------------------
echo ""
echo "==> Upgrading pip ..."
python3 -m pip install --quiet --upgrade pip

# ---------------------------------------------------------------------------
# Sidecar venv (lightweight — lives next to the repo on /workspace)
# ---------------------------------------------------------------------------
echo ""
echo "==> Setting up sidecar venv at ${SIDECAR_VENV} ..."
mkdir -p "$(dirname "${SIDECAR_VENV}")"
if [ ! -d "${SIDECAR_VENV}" ]; then
  python3 -m venv "${SIDECAR_VENV}"
fi
# shellcheck disable=SC1091
source "${SIDECAR_VENV}/bin/activate"
pip install --quiet --upgrade pip
pip install --quiet \
  "fastapi>=0.115" \
  "uvicorn[standard]>=0.32" \
  "pydantic>=2.9" \
  "httpx>=0.27" \
  "sse-starlette>=2.1" \
  "python-multipart>=0.0.12"
deactivate

# ---------------------------------------------------------------------------
# Clone NVIDIA/personaplex repo (moshi fork with PersonaPlex defaults)
# ---------------------------------------------------------------------------
echo ""
if [ ! -d "${PERSONAPLEX_REPO}" ]; then
  echo "==> Cloning NVIDIA/personaplex to ${PERSONAPLEX_REPO} ..."
  git clone https://github.com/NVIDIA/personaplex "${PERSONAPLEX_REPO}"
else
  echo "==> NVIDIA/personaplex already cloned at ${PERSONAPLEX_REPO}, pulling latest ..."
  (cd "${PERSONAPLEX_REPO}" && git pull --ff-only) || true
fi

# ---------------------------------------------------------------------------
# PersonaPlex venv — install NVIDIA's fork of moshi (not PyPI's vanilla moshi)
# ---------------------------------------------------------------------------
echo ""
echo "==> Setting up PersonaPlex venv at ${PP_VENV} ..."
mkdir -p "$(dirname "${PP_VENV}")"
if [ ! -d "${PP_VENV}" ]; then
  python3 -m venv "${PP_VENV}"
fi
# shellcheck disable=SC1091
source "${PP_VENV}/bin/activate"
pip install --quiet --upgrade pip
echo "==> Installing NVIDIA moshi fork from ${PERSONAPLEX_REPO}/moshi ..."
(cd "${PERSONAPLEX_REPO}" && pip install --quiet "moshi/.")
pip install --quiet huggingface_hub hf_transfer accelerate

# Customer-side STT (Kyutai) deps — webrtcvad for utterance segmentation,
# transformers for the model. Both go in the personaplex venv because the
# patched moshi.server imports them at runtime.
echo "==> Installing Kyutai STT deps (webrtcvad, transformers) into PP venv ..."
pip install --quiet "webrtcvad>=2.0.10" "transformers>=4.45"

# Apply VoxReach patches (idempotent) — adds server-side default text prompt
echo "==> Applying VoxReach patches to moshi/server.py ..."
SERVER_PY=$(ls "${PP_VENV}"/lib/python*/site-packages/moshi/server.py 2>/dev/null | head -1)
if [ -n "${SERVER_PY}" ]; then
  python "${POC_DIR}/runpod/patches/inject_default_prompt.py" "${SERVER_PY}" || \
    echo "    (patch failed — server will work, but the default-prompt feature won't activate)"
fi

# Quick CUDA sanity — fail fast if torch can't talk to the GPU
python - <<'PY'
import torch
print(f"   torch       {torch.__version__}")
print(f"   cuda        {torch.cuda.is_available()}")
if not torch.cuda.is_available():
    raise SystemExit("ERROR: torch.cuda.is_available() is False — wrong CUDA wheels for this pod's driver")
print(f"   GPU         {torch.cuda.get_device_name(0)}")
print(f"   VRAM        {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
PY

# ---------------------------------------------------------------------------
# Pre-pull PersonaPlex weights to the persistent cache
# ---------------------------------------------------------------------------
echo ""
echo "==> Pre-downloading PersonaPlex weights to ${HF_HOME} (~14 GB) ..."
python - <<'PY'
import os
from huggingface_hub import snapshot_download
print("   pulling nvidia/personaplex-7b-v1 ...")
snapshot_download(repo_id="nvidia/personaplex-7b-v1", token=os.environ["HUGGING_FACE_HUB_TOKEN"])
print("   done.")
PY

# Pre-pull Kyutai STT model used by the customer-side transcription patch.
# Skip with VOXREACH_SKIP_STT_PREFETCH=1 if you want a faster setup and don't
# mind a ~5s lazy-load on the first customer utterance.
if [ "${VOXREACH_SKIP_STT_PREFETCH:-0}" != "1" ]; then
  STT_MODEL_ID="${VOXREACH_STT_MODEL:-kyutai/stt-2.6b-en}"
  echo "==> Pre-downloading Kyutai STT weights (${STT_MODEL_ID}, ~6 GB) ..."
  python - <<PY
import os
from huggingface_hub import snapshot_download
snapshot_download(repo_id="${STT_MODEL_ID}", token=os.environ.get("HUGGING_FACE_HUB_TOKEN"))
print("   done.")
PY
fi

deactivate

# ---------------------------------------------------------------------------
# Node + web app
# ---------------------------------------------------------------------------
echo ""
if ! command -v node >/dev/null 2>&1; then
  echo "==> Installing Node 20 ..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y -qq nodejs
fi
echo "==> Installing web app deps ..."
cd "${POC_DIR}/web"
npm ci --silent

# ---------------------------------------------------------------------------
echo ""
echo "==> Disk usage after setup:"
df -h / "${WORKSPACE}" 2>/dev/null | head -3
echo ""
echo "==> Setup complete."
echo "==> Env file written to ${ENV_FILE}"
echo "==> On future pods: source ${ENV_FILE} && bash runpod/start.sh"
echo "==> On THIS pod: bash runpod/start.sh"
